version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Sabari@123
      MYSQL_DATABASE: realestate
      MYSQL_USER: root
      MYSQL_PASSWORD: Sabari@123
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 60s
      retries: 20
      interval: 10s
    networks:
      - mynetwork

  backend:
    # build:
    #   context: ./backend/spring-micro
    #   dockerfile: Dockerfile
    image: sabari038/test:version1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/login_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Sabari@123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  frontend:
    # build:
    #   context: ./frontend/myapp
    #   dockerfile: Dockerfile
    image: sabari038/test:frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge